# @package _global_

defaults:
  - _base_
  - _self_
  - scheduler: tsubame
  - experiment: example
  - override hydra/job_logging: disabled

# Job identification
output_dir: outputs
project_name: project
experiment_name: experiment

# Hydra configuration
hydra:
  output_subdir: hydra
  run:
    dir: ${hydra.sweep.dir}/${hydra.sweep.subdir}
  sweep:
    dir: ${output_dir}/${project_name}
    subdir: ${experiment_name}
